### ISSUE TITLE
"Follow me!"

### ISSUE THREAD

**Issue by jhaip** [jhaip/minecraft-put-that-there#10]
Ability for Jack to lead the player to an area.  Walks toward target while making sure the player isn't too far away.

**Comment by jhaip** [comment]
combine the new robot_state variable and add a flag like should_follow to make Jack follow when he is not told to do anything else.

**Comment by jmnoss** [comment]
Jack shouldn't follow after "Go there".  Are there other times when he shouldn't follow?

**Comment by jmnoss** [comment]
Jack follows by default until player tells him to stop or tells him to go somewhere.  Jack will start following again after completing a task or being instructed to follow.
