### ISSUE TITLE
If Jack is too far away, teleport him to you when you say "come here"

### ISSUE THREAD

**Issue by jhaip** [jhaip/minecraft-put-that-there#19]
[Entity.teleport()](https://hub.spigotmc.org/javadocs/spigot/) <-- Ignore this because we are teleporting Jack, not the owner.

**Comment by jhaip** [comment]
API updated in https://github.com/jhaip/botchallenge/commit/449ff7816e572236054ad8a5c361e339e7e4370d

**Comment by jmnoss** [comment]
Does robot.teleport(location) work?  It seems to just return False, but maybe I'm doing something wrong.

**Comment by jhaip** [comment]
robot.teleport(location) returns False when the location you are trying to teleport to already has a block there. If you look at the things the server prints out it should tell you where it tried to teleport to.  By pressing F3 in minecraft you can see the coordinates of things and verify if the location is what you expect it to be.
