### ISSUE TITLE
Ability to give the player items

### ISSUE THREAD

**Issue by jhaip** [jhaip/minecraft-put-that-there#2]
Jack has his own inventory and can mine blocks but he can't give them to the player.  In a real game a player would thrown them on the ground ('Q' command) and then the other player can pick them up.

We would have to extend the botchallenge API, both on the python and Java plugin side to support this.

**Comment by jhaip** [comment]
[World.dropItem() or World.dropItemNaturally()](https://hub.spigotmc.org/javadocs/spigot/)

**Comment by jhaip** [comment]
robot.drop_item(item type, amount) added to botchallenge API here:

https://github.com/jhaip/botchallenge/commit/d5f33259b2292d96a5528cde7ed5bc671eac3bb1

**Comment by jmnoss** [comment]
Parsing amounts (numbers) from speech is impractical... Any better ideas?  Maybe instead we could use "a", "one", "some", "lots", "all" and translate them into numbers.

**Comment by jhaip** [comment]
Maybe for now just drop all of that block type Jack has in his inventory?
