### ISSUE TITLE
understanding of "this", "that", or "those"

### ISSUE THREAD

**Issue by jhaip** [jhaip/minecraft-put-that-there#3]
Based on what the player is currently looking at.  Would require some sort of function that returns a list of the blocks the player is looking at.  Would require extending the python api and Java plugin for botchallenge.
1. Use the "looking at" block built into minecraft that gives the coordinate of the block the player is looking at within a short radius.
2. To be able to see far away things we could use the vector of the player's view and do some raycasting to return a list of blocks the player can see.  Would probably be hard.

**Comment by jhaip** [comment]
Guy did raycasting in pure command blocks [https://www.youtube.com/watch?v=hxaC3D6c3oA](here)

**Comment by jhaip** [comment]
[LivingEntity.getTargetBlock() or LivingEntity.getLineOfSight()](https://hub.spigotmc.org/javadocs/spigot/)

limited to a single block the player is looking at but we can set a max distance very far away!

**Comment by jhaip** [comment]
[LivingEntity.getEyeLocation()](https://hub.spigotmc.org/javadocs/spigot/) to give us the vector that the player is looking

**Comment by jhaip** [comment]
Good reference of modifying the botchallenge API on both the python and java plugin side.
[https://github.com/katharosada/botchallenge/commit/7d37a6a6cb209f29bd79b0cf6cc9f238de81f297](https://github.com/katharosada/botchallenge/commit/7d37a6a6cb209f29bd79b0cf6cc9f238de81f297)

**Comment by jhaip** [comment]
botchallenge API extended to included robot.get_block_type_at(location) in https://github.com/jhaip/botchallenge/commit/141dd9b702847b88d6790c6089a04dee9897caa7 and robot.get_owner_target_block() in https://github.com/jhaip/botchallenge/commit/bd7b6dde24cf8030a8a033cf1d21faa8a7d5d88d

These two functions should be all that is needed to start doing meaningful things from a "this", "that", or "those" command.

**Comment by jmnoss** [comment]
this/that/those/these refers to wherever player is looking.  Jack can now correctly respond to questions/requests such as "do you have that in your inventory", "gather some of that", and "give me some of that".
